train_dataset: cub
train_dataset_args: {split: train, augment: crop}
val_dataset: cub
val_dataset_args: {split: test, augment: crop}
fs_dataset: cub
fs_dataset_args: {split: test, augment: crop}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 200}

batch_size: 128
max_epoch: 120
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [90]}

save_epoch: 5
visualize_datasets: false
